### PR TITLE
Python 3 compatibility.

### PR DESCRIPTION
**Pull request by alxp**

### CODE REVIEW

**Comment by jonathangreen** [comment]
This is awesome! Welcome back! 🎉 I was both surprised and excited to see a PR this morning from ***the*** @alxp.

Haven't tested it yet, but PR looks good to me at first brush. 

One housekeeping thing before this can be merged we need a signed [CLA](https://github.com/Islandora/islandora/wiki/Contributor-License-Agreements) from you. This applies to any of the repos managed by the [Islandora Foundation](https://islandora.ca/if).

**Comment by alxp** [comment]
Hi @jonathangreen ,

Tanks for the quick reply. I tested the script using python 2.7 and 3.6.4, testing the paths of: missing xml file, valid connection and invalid connection and all worked in both versions.

WRT the CLI, I'm currently working on a short-term basis for Robertson Library. So my working for them mean I am already covered by their CLA or do I need to sign one separately? I am happy to do both.

**Comment by DiegoPino** [comment]
@jonathangreen @alxp we need to ask probably (@dannylamb ping). Short term work relationships and CLA play much better together if the pull/commits come from the institution's Github account, but maybe there is an exception here? Thanks for this contribution

**Comment by whikloj** [comment]
👍  to PRs coming from the covered institutions Github if that is possible.

**Comment by alxp** [comment]
OK, I'll sign a CLA but in the mean time I'll open a new PR from the goblin org

**Comment by alxp** [comment]
Moved to https://github.com/Islandora-Labs/drupal_filter_validator/pull/2

**Comment by dannylamb** [comment]
@alxp Welcome back. I'm sure you would've been ok under UPEI's cCLA, but thanks for sending in an iCLA to make things clear.

**Pull request closed without merging**
